import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Main from "../components/Main";
import Items from "../components/Items";
import Products from "../components/Products";
import { client } from "../lib/client";
import React, { useEffect, useState } from "react";
import useSWR from "swr";

const inter = Inter({ subsets: ["latin"] });

export default function Home({data}) {

  const {data, error} = useSWR('*[_type == "post"]')

  // const[searched, setSearched] = useState([])
  // const getSearched = async()=>{
  //   const url = '*[type == "post"]'
  //   const data = await client.fetch(url)
  //   setSearched(data);
  // }
  // useEffect(() => {
  //   getSearched();
  // }, []);
  
  // console.log('searched:', searched);

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Main/>
        <Items/>
        <Products/>
      </main>
    </div>
  );
}



export const getServerSideProps = async()=>{
  const query = '*[_type == "post"]';
  const data = await client.fetch(query);
  return {
    props: {
      data,
    }
  }
}

